data watersheds;
	infile 'WATERSHD.txt';
	input x1 x2 x3 x4 x5 x6 x7 x8 x9 Q;
run;
data watersheds;
	set watersheds;
	LQ=log(Q);
	Lx1=log(x1);
	Lx2=log(x2);
	Lx3=log(x3);
	Lx4=log(x4);
	Lx5=log(x5);
	Lx6=log(x6);
	Lx7=log(x7);
	Lx8=log(x8);
	Lx9=log(x9);
run;
proc reg data=watersheds;
	model LQ = Lx1 Lx2 Lx3 Lx4 Lx5 Lx6 Lx7 Lx8 Lx9 / selection=stepwise sle=0.5 sls=0.2;
run;
quit;
proc reg data=watersheds;
	model LQ = Lx1 Lx2 Lx3 Lx4 Lx5 Lx6 Lx7 Lx8 Lx9 / selection=backward sle=0.5 sls=0.2;
run;
quit;
proc reg data=watersheds;
	model LQ = Lx1 Lx2 Lx3 Lx4 Lx5 Lx6 Lx7 Lx8 Lx9 / selection=forward sle=0.5 sls=0.2;
run;
quit;
proc reg data=watersheds;
	model LQ = Lx1 Lx2 Lx3 Lx4 Lx5 Lx6 Lx7 Lx8 Lx9 / selection=cp best=20;
	plot cp.*np. / chocking=red  cmallows=blue
         vaxis=0 to 15 by 5 cframe=ligr;
run;
quit;
